#include <iostream>
#include <algorithm>
#include <unordered_map>
#include <queue>
#include <vector>

#define SIZE 100

int mp[SIZE][SIZE]; // adjacency matrix, real distance

int heuristic[SIZE]; // heuristic values

int start, goal; // from Arad to Bucharest

void input()
{
}

void greedyBestFirstSearch(int start, int goal)
{
}

void printPath()
{ // put path generated by greedyBestFirst and also output the real cost
}

int main()
{
    input();
    greedyBestFirstSearch(start, goal);
}